### ISSUE TITLE
Search feature.  

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/thumbwar-ios-client#57] opened 2015-02-10 02:58 UTC
Need a Field where you can search content or users

**Comment by smummolo** [comment] 2015-02-16 19:29
lets add a simple top bard with a search field + button that appears when you pull down from the top of the feed (pulling down from the top of the feed ALSO updates the feed)

**Comment by adamespn** [comment] 2015-02-17 01:36
"bard" means "bar", I assume?
How are results displayed? Is there a particular search methodology you want to use? Can I sort/filter results by relevance, recency, etc.? How do I get back to the view I had before I searched? I'm a little confused about what it looks like when I pull to refresh/search. Do I really see a search widget AND a spinner that tries to update? It might work but it sounds a little odd.

**Comment by smummolo** [comment] 2015-03-09 17:17
no i meant lets add a minstrel to the app ;P

yes "search bar" - sorry. 

re: what it looks like - i envisioned the simple version just acting like a filtered view of the feed. Search "lakers" - get a feed made of posts relating to lakers. 

Filtered search results feed should be labeled in the header bar "'search term' feed" - just text in the header

No results shows very simple "sorry no results" message in the feed area. 

To get back to non filtered feed - just tap home or my feed in the bottom nav.

**Comment by adamespn** [comment] 2015-03-16 01:09
@CodySwannGT can you confirm that I can filter on mine or all, then by a search term, and also paginate at the same time?

**Comment by adamespn** [comment] 2015-05-01 10:53
closing as duplicate of #77

**Closed by adamespn** 2015-05-01 10:53 UTC
Labels: feedback
