### ISSUE TITLE
Bet view

### ISSUE THREAD

**Issue by jiakeliu** [gunnertech/thumbwar-ios-client#85] opened 2015-04-06 23:35 UTC
This is the detailed bet view after a user clicks on a post. In this view, the user can leave comments and choose sides.

![bet view](https://cloud.githubusercontent.com/assets/1039583/7014532/eb341c18-dc7a-11e4-92f8-dca29912b249.jpg)

**Comment by jiakeliu** [comment] 2015-04-07 02:20
![detail](https://cloud.githubusercontent.com/assets/1039583/7016003/fa3d5640-dc91-11e4-9bfa-b8173630a043.jpg)

**Comment by jiakeliu** [comment] 2015-04-26 06:31
Build 26 Bugs:
-Bet content does not show up
-Bet prize/stake does not show up
-Comment does not show up until a manual refresh
-Siding does not show up on the right side correctly

**Comment by adamespn** [comment] 2015-04-26 12:55
Noticed that the prize, comments bar (including ellipses), etc. are not visible in this mock up.
Are we putting any of those things here? Vertical space is a little limited right now.

**Comment by adamespn** [comment] 2015-04-26 13:16
-Bet content does not show up - in progress

-Bet prize/stake does not show up - please update design

-Comment does not show up until a manual refresh - cannot reproduce

-Siding does not show up on the right side correctly - fixed

**Comment by jiakeliu** [comment] 2015-04-26 20:01
Here's the new mockup adding back the Prize field and the elipses.

![detail_prize](https://cloud.githubusercontent.com/assets/1039583/7339013/5f7fab66-ec14-11e4-9de3-4ff0b17752ea.jpg)

**Comment by jiakeliu** [comment] 2015-05-02 01:49
@adamespn is the ellipses added back to the bet detail screen as shown in the mockup?

**Comment by adamespn** [comment] 2015-05-07 03:37
the ellipses is there and tappable - not sure why it's not visible - have to check

**Comment by adamespn** [comment] 2015-05-07 04:01
On the bet pic: If the pic aspect ratio is different than the containing rectangle do you want to:
1) Crop it
2) Stretch/fill it
3) Pillarbox/Letterbox it?

**Comment by jiakeliu** [comment] 2015-05-07 04:16
Resize the image proportionally to fill either width or height, which ever is smaller, then crop the rest.

**Comment by adamespn** [comment] 2015-05-08 00:24
ah - the ellipses I have is blue. There is no ellipses in the psd for the war detail mock. I'm repurposing the signal ellipses from the header. If you can send or point me to white ellipses at some point that would be great - closing

**Closed by adamespn** 2015-05-08 00:24 UTC
Labels: ui/ux
