### ISSUE TITLE
App crashes when creating a Thumbwar.

### ISSUE THREAD

**Issue by DaryMerckensGT** [gunnertech/thumbwar-ios-client#42] opened 2015-02-01 05:43 UTC
Input values:
  What => "something"
  @Who => "Cody Swann" (Type "C", select "Cody Swann FB")
  $Prize => "food"

Hit "DECLARE WAR" and app closes out.

**Comment by adamespn** [comment] 2015-02-01 05:49
probably a dupe of #32 but let's leave this one open for now

**Closed** 2015-02-02 04:45 UTC
Labels: bug
